### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#389]
- [x] One issue is related mypy failing for numpy wheels (fixed in https://github.com/JDASoftwareGroup/kartothek/pull/386)
- [x] Other issue has to do with pyarrow: `E           AttributeError: module 'pyarrow.compute' has no attribute 'equal'`. See: https://github.com/JDASoftwareGroup/kartothek/runs/1659863066?check_suite_focus=true (fixed in #391 )
